
# C++
language: cpp

# Run on both Ubuntu 14.04 and OS X 10.9.5
os:
  - linux
  - osx
sudo: required
dist: trusty

# Run both Debug and Releas
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:keithw/glfw3 -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sed -i 's/us-central1.gce/us-central1.gce.clouds/' /etc/apt/sources.list && sudo apt-get -qq update; fi

install:
  # Necessary packages
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install xorg-dev libglfw3-dev -y; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glfw3; fi

  # Pull github dependencies
  - ./UpdateDependencies.bash

script:
  - mkdir Build && cd Build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make
  - ./bin/TestUnits
